"""Update Payment model - support multiple payments per booking

Revision ID: 19d07e78b112
Revises: 8475d1a94b7b
Create Date: 2026-08-30 14:38:47.318656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d07e78b112'
down_revision = '8475d1a94b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screenshot_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verified_by', sa.Integer(), nullable=True))
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['verified_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.drop_column('verified_by')
        batch_op.drop_column('screenshot_path')

    # ### end Alembic commands ###
