"""Add TestResult model

Revision ID: 701bf92d9e22
Revises: d8bbdfd7599f
Create Date: 2026-08-25 12:40:48.963488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701bf92d9e22'
down_revision = 'd8bbdfd7599f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=True),
    sa.Column('entered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_results')
    # ### end Alembic commands ###
