"""Add Sample model

Revision ID: d8bbdfd7599f
Revises: 3a1087f46bb5
Create Date: 2026-08-25 12:17:15.180962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bbdfd7599f'
down_revision = '3a1087f46bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_item_id', sa.Integer(), nullable=False),
    sa.Column('sample_code', sa.String(length=30), nullable=False),
    sa.Column('collected_by', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_item_id'], ['booking_items.id'], ),
    sa.ForeignKeyConstraint(['collected_by'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samples')
    # ### end Alembic commands ###
